---
title       : Israeli Lorrety Results 1994-2015
subtitle    : 
author      : Ido Lustig
job         : 
framework   : io2012        # {io2012, html5slides, shower, dzslides, ...}
highlighter : highlight.js  # {highlight.js, prettify, highlight}
hitheme     : tomorrow      # 
widgets     : []            # {mathjax, quiz, bootstrap}
mode        : selfcontained # {standalone, draft}
knit        : slidify::knit2slides
---


## About the tool
This tool is designed to provide some basic and general statistics on the results of the Israeli Lottery between the years.

The user of the tool can chose a timeframe on which she can get the following:
* Top X frequent numbers (X can be any integer between 1 and 10)  
* Numbers frequency (draws per number)  
* Inspect the raw data    

--- .class #id 

## Source of the data  
Data is taken from http://www.pais.co.il/Lotto/Pages/last_Results.aspx?download=1

--- .class #id 

## Using the tool
* In the 'Explore Results' tab  
  * Select start and end dates (under Timeline)  
  * Select number of most frequent numbers to present (under Number of Top Results)  
* Review the most frequent numbers within the chosen timeframe under the "Most Frequent" tab  
* Review a numbers frequency plot under the "Data Visualization" tab  
* Review and filter/sort the raw data under the "Raw Data" tab  

--- .class #id 


